-- 0012: 보안 지혈 (STEP 0) — docs/db-restructure-plan.md §7 STEP 0
--
-- 배경(실측 2026-07-28):
--   (1) rail_steps / rail_compositions 는 RLS가 꺼져 있었다 (pg_class.relrowsecurity = false).
--       그리고 Supabase 기본값으로 모든 테이블이 anon 에게 INSERT/UPDATE/DELETE/TRUNCATE 를 그랜트한다.
--       → 브라우저에 노출되는 NEXT_PUBLIC_SUPABASE_ANON_KEY 만으로 스캐폴딩 레일을 통째로 지울 수 있었다.
--       실증: POST /rest/v1/rail_steps {} → 23502(NOT NULL 위반, 권한은 통과)
--             POST /rest/v1/questions  {} → 42501(RLS 차단) ← 정상 동작 대조군
--   (2) src/components/survey/CallSurvey.tsx 가 survey_responses 에 insert 하는데 테이블이 없었다.
--       → 설문 응답이 저장되지 않고 있었다.
--
-- 방침: RLS를 "유일한 방어선"으로 두지 않는다. 권한(GRANT) 자체를 읽기 전용으로 되돌리고,
--       쓰기가 필요한 테이블에만 다시 열어준다. 새 테이블에 RLS를 켜는 걸 잊어도 안 뚫린다.
-- 관리 스크립트(scripts/*.js)는 SUPABASE_DB_URL = postgres 역할로 접속하므로 영향 없음.

begin;

-- =========================================================
-- (A) survey_responses 신설
-- =========================================================
create table if not exists survey_responses (
  id           bigint generated by default as identity primary key,
  user_id      uuid,                       -- 비로그인 응답 허용 (CallSurvey가 null을 넣는다)
  question_key text not null,
  answer       text not null,
  created_at   timestamptz not null default now()
);

alter table survey_responses enable row level security;
drop policy if exists "survey insert for all" on survey_responses;
create policy "survey insert for all" on survey_responses for insert with check (true);
drop policy if exists "survey read own" on survey_responses;
create policy "survey read own" on survey_responses for select using (auth.uid() = user_id);

-- =========================================================
-- (B) RLS 미적용 테이블 활성화
-- =========================================================
alter table rail_steps        enable row level security;
alter table rail_compositions enable row level security;

drop policy if exists "read for all" on rail_steps;
create policy "read for all" on rail_steps for select using (true);
drop policy if exists "read for all" on rail_compositions;
create policy "read for all" on rail_compositions for select using (true);

-- =========================================================
-- (C) learner_answer_log — 전체 공개 읽기 차단
-- =========================================================
-- 기존 정책은 USING (true) 라 누구나 남의 답안을 전부 읽을 수 있었다.
-- 다만 src/lib/profile.ts 가 신규 계정 리포트를 채우려고 **데모 UUID의 로그를 일부러 읽는다**.
-- 그래서 본인 행 + 데모 baseline 행만 허용한다 (실계정 간 열람은 차단).
--   ⚠️ 남은 한계: /api/tutor 는 anon 키로 서버에서 조회하므로 auth.uid()가 null 이다.
--      → countPriorTagWrongs(반복 오답 시 추가 단계 판정)가 0을 돌려준다.
--      완전한 해결은 서버 전용 service_role 키 도입(별도 작업). STEP 6에서 learning_events 로 정리.
drop policy if exists "read for all" on learner_answer_log;
drop policy if exists "read own or demo baseline" on learner_answer_log;
create policy "read own or demo baseline" on learner_answer_log for select
  using (auth.uid() = learner_id
         or learner_id = '11111111-1111-4111-8111-111111111111'::uuid);

-- =========================================================
-- (D) user_profiles 중복 정책 정리 (4개 → 1개)
-- =========================================================
drop policy if exists "users can insert own profile"  on user_profiles;
drop policy if exists "Users can insert own profile"  on user_profiles;
drop policy if exists "Users can update own profile"  on user_profiles;
drop policy if exists "users can read own profile"    on user_profiles;
drop policy if exists "본인 프로필만 접근"              on user_profiles;
create policy "본인 프로필만 접근" on user_profiles for all
  using (auth.uid() = id) with check (auth.uid() = id);

-- =========================================================
-- (E) 권한 되돌리기 — 여기가 핵심
-- =========================================================
-- 1) 전 테이블에서 쓰기 권한 회수
revoke insert, update, delete, truncate, references, trigger
  on all tables in schema public from anon, authenticated;

-- 2) 읽기는 유지 (RLS가 행 단위로 다시 거른다)
grant select on all tables in schema public to anon, authenticated;

-- 3) 쓰기가 실제로 필요한 곳만 다시 열기
grant insert on learner_answer_log to anon, authenticated;  -- 답안 기록
grant insert on survey_responses   to anon, authenticated;  -- 설문 응답
grant insert on fgi_responses      to anon, authenticated;  -- FGI 설문 응답
grant insert, update on user_profiles to authenticated;     -- 온보딩 프로필 (RLS가 본인 행으로 제한)
revoke select on user_profiles from anon;                   -- 비로그인은 프로필 조회 불가

-- 4) 앞으로 만들 테이블도 기본 읽기 전용 — "RLS 켜는 걸 잊어도 안 뚫리게"
--    ※ 이 문(alter default privileges)은 실행 역할(postgres) 이 만든 테이블에만 적용된다.
--       대시보드에서 다른 역할로 만든 테이블은 여전히 수동 확인 필요.
alter default privileges in schema public
  revoke insert, update, delete, truncate on tables from anon, authenticated;

commit;
