-- 0028: 실전 모의고사 회차 (YBM 실전토익 LC/RC 1000)
--
-- 무엇을 담나
--   교재 4권(LC 1·2권 · RC 1·2권)에서 뽑은 **회차 단위 문항 4000개**를 담을 자리.
--   추출 파이프라인은 scripts/extract_mock_all.py, 완결성 감사는 scripts/audit_mock_extract.py.
--
-- 왜 기존 lectures 에 못 붙이나
--   questions.lecture_id 는 NOT NULL 이고 lectures 는 **강의**(LC-P1-01 = 1강)다.
--   모의고사 문항은 어느 강의에도 속하지 않는다 — 한 회차가 Part 1~4 를 가로지르고,
--   순서(1~100번)와 회차가 정체성의 전부다. 억지로 가짜 강의 행을 만들면
--   강의 목록·레일·아이템이 전부 그 가짜를 실제 강의로 세게 된다(화면 4곳이 lectures 를 센다).
--   → lecture_id 를 nullable 로 풀고, 모의고사 문항은 mock_test_id 로 붙인다.
--     문항 하나는 둘 중 정확히 한쪽에 속한다(questions_owner_chk).
--
-- ⚠️ 매일 03:00 KST 크론(gcp/sync-questions-fn)과의 관계
--   크론은 시트의 question_id 로 `on conflict (question_code) do update` 한다 — **삭제는 안 한다.**
--   모의고사 문항 코드는 'YBM-' 로 시작해 시트 코드('LC-P1-01-Q001')와 겹치지 않으므로
--   크론이 건드리지 않는다. 반대로 이 마이그레이션도 시트 문항을 건드리지 않는다.
--   (0014 가 겪은 "밤마다 되돌아간다" 문제를 애초에 안 만드는 방식)

-- ※ 다른 마이그레이션과 달리 begin;/commit; 을 쓰지 않는다.
--    Supabase 대시보드 SQL 편집기가 이미 자체 트랜잭션 안에서 실행하기 때문에 충돌한다.
--    run-migration.js(node-pg) 로 돌릴 때도 파일 전체가 한 쿼리라 어차피 암묵적 트랜잭션이다.

-- =========================================================
-- (A) 회차
-- =========================================================
create table if not exists mock_tests (
  id          bigint generated by default as identity primary key,
  test_code   text not null unique,                    -- 'YBM-LC1-T01'
  source      text not null,                           -- 'YBM 실전토익 LC 1000'
  book        smallint not null check (book between 1 and 2),
  area        text not null check (area in ('LC', 'RC')),
  test_no     smallint not null check (test_no between 1 and 10),
  title       text not null,                           -- 'LC 1권 TEST 1'
  -- 실전은 LC 1~100 / RC 101~200 번을 쓴다. 화면이 번호를 그대로 보여주므로 범위를 남긴다
  no_from     smallint not null,
  no_to       smallint not null,
  created_at  timestamptz not null default now(),
  unique (source, book, area, test_no)
);

comment on table mock_tests is
  '실전 모의고사 한 회차(LC 100문항 또는 RC 100문항). 문항은 questions.mock_test_id 로 붙는다.';
comment on column mock_tests.no_from is
  '그 회차의 첫 문항 번호. LC=1, RC=101. 화면은 교재와 같은 번호를 보여준다.';

-- =========================================================
-- (B) 문항을 회차에 붙인다
-- =========================================================
alter table questions
  add column if not exists mock_test_id bigint references mock_tests(id) on delete cascade,
  add column if not exists question_no  smallint;

comment on column questions.mock_test_id is
  '실전 모의고사 회차. 강의 문항은 null (그쪽은 lecture_id 를 쓴다).';
comment on column questions.question_no is
  '회차 안 문항 번호(LC 1~100 / RC 101~200). 출제 순서가 곧 시험지 순서다.';

-- lecture_id 를 풀어 준다. 기존 행은 전부 값이 있으므로 데이터 변화 없음.
alter table questions alter column lecture_id drop not null;

-- 문항은 강의 **또는** 회차 중 한쪽에는 반드시 속한다. 어디에도 안 붙은 고아 문항을 막는다.
alter table questions drop constraint if exists questions_owner_chk;
alter table questions add constraint questions_owner_chk
  check (lecture_id is not null or mock_test_id is not null);

-- 한 회차에 같은 번호가 두 번 들어오지 않게. (모의고사 행에만 적용 — 강의 문항은 question_no 가 null)
create unique index if not exists questions_mock_no_uniq
  on questions (mock_test_id, question_no)
  where mock_test_id is not null;

create index if not exists questions_mock_idx
  on questions (mock_test_id, question_no);

-- =========================================================
-- (C) 지문 음원 — Part 3·4 는 지문 하나가 곧 음원 하나다
-- =========================================================
-- 0014 는 passage_sentences.audio_url(문장 구간)만 뒀다. 교재 음원은 문장이 아니라
-- **세트 단위**로 끊겨 있어서(Test 01_Part 3_32-34.mp3) 붙일 자리가 없었다.
-- 문항 단위 음원(Part 1·2)은 기존대로 questions.content.audio_url 을 쓴다.
alter table passages add column if not exists audio_url text;

comment on column passages.audio_url is
  '지문 전체 음원(LC Part 3·4 세트 mp3). 문장 구간은 passage_sentences.audio_url.';

-- =========================================================
-- (D) 권한 — 0012 의 방침 그대로 (읽기 전용)
-- =========================================================
alter table mock_tests enable row level security;
drop policy if exists "read for all" on mock_tests;
create policy "read for all" on mock_tests for select using (true);

revoke insert, update, delete, truncate on mock_tests from anon, authenticated;
grant select on mock_tests to anon, authenticated;
